// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"events-manager/infrastructure/app"
	"events-manager/infrastructure/http/server"
	"events-manager/infrastructure/rabbit"
	"events-manager/pkgs/logger"
)

// Injectors from wire.go:

func CreateApp() *app.App {
	appSettings := app.LoadAppSettings()
	settings := app.GetLoggerSettings(appSettings)
	sugaredLogger := logger.NewLogger(settings)
	engine := http.NewServer()
	rabbitSettings := app.GetRabbitSettings(appSettings)
	rabbitClient := rabbit.NewRabbitClient(sugaredLogger, rabbitSettings)
	appApp := app.NewApp(sugaredLogger, engine, appSettings, rabbitClient)
	return appApp
}
