services:
  events-manager:
    # change to image if you pre built
    build: ./events-manager
    ports:
      - 8080:8080
    env_file:
      - ./events-manager/.env
    volumes:
      - ./events-manager:/app
    depends_on:
      rabbit:
        condition: service_healthy
      #postgres_db: 
      #  condition: service_healthy

  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-q", "-d", "devdb", "-U", "dev" ]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10
    environment:
      POSTGRES_PASSWORD: 1234

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  front:
    build:
      ./front
    volumes:
      - ./front:/app
    ports:
      - 4200:4200
  
  rabbit:
    build: ./configs/rabbit
    ports: 
        - "15672:15672"
        - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      hostname: 'rabbit'
      RABBITMQ_ERLANG_COOKIE: 'secret cookie of julian'

volumes:
  postgres_data:
  mongo_data: