FROM golang:alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY ["go.mod", "go.sum", "./"]
RUN go mod download && go mod verify

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
#CMD ["go", "run", "/app/cmd/server"]