FROM golang:alpine

WORKDIR /app

COPY ["go.mod", "go.sum", "./"]
RUN go mod download && go mod verify

COPY . .
RUN ["go", "build", "-C", "cmd/server", "-o", "app"]

EXPOSE 8080

CMD ["go", "run", "/app/cmd/server"]